1. Даны значения зарплат из выборки выпускников: 100, 80, 75, 77, 89, 33, 45, 25, 65, 17, 30, 24, 57, 55, 70, 75, 65, 84, 90, 150. Посчитать (желательно без использования статистических методов наподобие std, var, mean) среднее арифметическое, среднее квадратичное отклонение, смещенную и несмещенную оценки дисперсий для данной выборки.

In [2]:
import numpy as np
data=np.array([100, 80, 75, 77, 89, 33, 45, 25, 65, 17, 30, 24, 57, 55, 70, 75, 65, 84, 90, 150])

In [55]:
data.shape

(20,)

In [7]:
data.sort()

In [8]:
data

array([ 17,  24,  25,  30,  33,  45,  55,  57,  65,  65,  70,  75,  75,
        77,  80,  84,  89,  90, 100, 150])

In [12]:
middle= data.sum()/data.shape

In [13]:
middle

array([65.3])

In [41]:
middle2_array=[]
for i in data:
    middle2=(i-middle)
    middle2_array.append(middle2)
std = ((np.array(middle2_array)**2).sum()/data.shape)**(1/2)  


In [57]:
std_smesh = (((data-middle)**2).sum()/(len(data)-1))**(1/2)

In [58]:
std

array([30.8238544])

In [61]:
std_smesh

31.62460734101981

2. В первом ящике находится 8 мячей, из которых 5 - белые. Во втором ящике - 12 мячей, из которых 5 белых. Из первого ящика вытаскивают случайным образом два мяча, из второго - 4. Какова вероятность того, что 3 мяча белые?

In [66]:
P1= 5/8*4/7*5/12*7/11*6/10*5/9


In [67]:
P2=5/8*3/7*5/12*4/11*7/10*6/9

In [68]:
P3=3/8*2/7*5/12*4/11*3/10*7/9

In [70]:
P=P1+P2+P3
P

0.05429292929292929

3. На соревновании по биатлону один из трех спортсменов стреляет и попадает в мишень. Вероятность попадания для первого спортсмена равна 0.9, для второго — 0.8, для третьего — 0.6. Найти вероятность того, что выстрел произведен: a). первым спортсменом б). вторым спортсменом в). третьим спортсменом.

In [93]:
P=1/3*0.9+1/3*0.8+1/3*0.6
P
P1=1/3*0.9/P
P2=1/3*0.8/P
P3=1/3*0.6/P
print(P1,P2,P3, P1+P2+P3)

0.391304347826087 0.3478260869565218 0.2608695652173913 1.0


4. В университет на факультеты A и B поступило равное количество студентов, а на факультет C студентов поступило столько же, сколько на A и B вместе. Вероятность того, что студент факультета A сдаст первую сессию, равна 0.8. Для студента факультета B эта вероятность равна 0.7, а для студента факультета C - 0.9. Студент сдал первую сессию. Какова вероятность, что он учится: a). на факультете A б). на факультете B в). на факультете C?

In [91]:
#соотношение студентов в группах
#A=B=1/4, C=1/2
P = 1/4*0.8+1/4*0.7+1/2*0.9
P_A1 = 1/4*0.8/P
P_B1 = 1/4*0.7/P
P_C1 = 1/2*0.9/P
print(P, P_A1, P_B1, P_C1, P_A1+P_B1+P_C1)

0.825 0.24242424242424246 0.21212121212121213 0.5454545454545455 1.0


5. Устройство состоит из трех деталей. Для первой детали вероятность выйти из строя в первый месяц равна 0.1, для второй - 0.2, для третьей - 0.25. Какова вероятность того, что в первый месяц выйдут из строя: а). все детали б). только две детали в). хотя бы одна деталь г). от одной до двух деталей?

In [71]:
p1=0.1
p2=0.2
p3=0.25

а.

In [73]:
P_all= p1*p2*p3
P_all

0.005000000000000001

б.

In [72]:
#найдем вероятности, что приборы не выйдут из строя 
q1=1-p1
q2=1-p2
q3=1-p3

In [74]:
#комбинации вероятности выхода двух приборов из строя
P_A1=p1*p2*q3
P_A2=q1*p2*p3
P_A3=q1*p2*p3
P_fault_2=P_A1+P_A2+P_A3
P_fault_2

0.10500000000000001

в.

In [78]:
#вероятность, что ни один прибор не выйдет из строя
P_ok=q1*q2*q3
#вероятность, что хотябы один выйдет = 1-P_ok
P_fault_1 = 1-P_ok
P_ok
P_fault_1

0.45999999999999996

г.

In [81]:
P_fault_1or2=P_fault_1+P_fault_2
P_fault_1or2

0.565